#include "stdafx.h"

BEGIN_INIT_QUERY(TPatchSvr)
	PREDEFINE_QUERY(CSPLoadService)
	PREDEFINE_QUERY(CTBLVersion)
	PREDEFINE_QUERY(CSPMinBetaVer)
	PREDEFINE_QUERY(CTBLPreVersion)
	PREDEFINE_QUERY(CSPPreComplete)
	PREDEFINE_QUERY(CTBLInterface)
END_INIT_QUERY()